---
- name: Install packages to use apt over HTTPS
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - python-pip
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
   name: docker
   executable: pip

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name:
  apt:
   pkg:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   update_cache: yes
  notify: systemd docker
